# SPDX-FileCopyrightText: Copyright 2025 The Policy Labs Project Contributors
# SPDX-License-Identifier: Apache-2.0

name: Check Copyright Boilerplates

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        extension:
        - go
        - sh
        - yaml
        - yml
        - html
        - css
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash
        - extension: yaml
          language: YAML
        - extension: yml
          language: YAML
        - extension: proto
          language: protobuf

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: boilerplate-check-1
        continue-on-error: true
        uses: chainguard-dev/actions/boilerplate@805da2efdffdc42b8afd8880e575a48b471ef544 # v1.6.37
        with:
          boilerplate-directory: "./hack/boilerplates"
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}

      - id: boilerplate-check-2
        if: steps.boilerplate-check-1.outcome == 'failure'
        uses: chainguard-dev/actions/boilerplate@805da2efdffdc42b8afd8880e575a48b471ef544 # v1.6.37
        with:
          boilerplate-directory: "./hack/boilerplates"
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
